name: Translation Check

on:
  workflow_dispatch:
  push:
    paths:
      - '*.json'
  pull_request:
    paths:
      - '*.json'

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Translations
        uses: krzysztoff1/translation-check@v1.1.0
        with:
          main_translation_path: './en.json'
          translation_paths: './de.json,ru.json,pl.json,pt.json'
